CREATE TABLE `AUTHORS` (
  `ID` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `NAME` varchar(60) NOT NULL,
  `BIRTH_DATE` date NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `AUTHORS` (`ID`, `NAME`, `BIRTH_DATE`) VALUES
(1, 'Adams Douglas', '1952-07-14');


CREATE TABLE `BOOKS` (
  `ID` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `TITLE` varchar(60) NOT NULL,
  `RELEASE_DATE` date NOT NULL,
  `AUTHOR_ID` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO `BOOKS` (`ID`, `TITLE`, `RELEASE_DATE`, `AUTHOR_ID`) VALUES
(1, 'The Hitchhiker\'s Guide to the Galaxy', '1979-07-14', 1);

ALTER TABLE `BOOKS` ADD CONSTRAINT `books_ibfk_1` FOREIGN KEY (`AUTHOR_ID`) REFERENCES `AUTHORS` (`ID`);
